### ISSUE TITLE
Cosmetic Changes for Developer Guide

### ISSUE THREAD

**Issue by kwokyto** [AY2021S2-CS2113-T10-1/tp#139]
- [x] Adjust Diagram Sizes for DG
- [x] Finalise number of LoC in UG, DG, kwokyto.dg, readme.md

**Comment by Leeyp** [comment]
Fix broken multiquote code tags under _Appendix: Instructions for Manual Testing_

![image](https://user-images.githubusercontent.com/2010527/112969618-ff000e80-917f-11eb-87cc-d564f16ee835.png)
