### ISSUE TITLE
Review comments for your DG

### ISSUE THREAD

**Issue by stephlewyh** [AY2021S2-CS2113-T10-1/tp#201]
1.  Value proposition looks good. But, what type of user are you targeting? 
<img width="619" alt="Screen Shot 2021-04-04 at 12 00 50 AM" src="https://user-images.githubusercontent.com/2998854/113484010-d27a2880-94d8-11eb-867d-e6db9620354e.png">

2. Architecture diagram: User interacts with Utilities? not UI? Conventionally utility components contains just static methods and cannot be instantiated. 
<img width="304" alt="Screen Shot 2021-04-04 at 12 00 13 AM" src="https://user-images.githubusercontent.com/2998854/113483989-bd9d9500-94d8-11eb-98c4-4d2aef346648.png"> 
<img width="573" alt="Screen Shot 2021-04-04 at 12 04 02 AM" src="https://user-images.githubusercontent.com/2998854/113484126-44eb0880-94d9-11eb-904a-204a91c277b2.png">

This is better. But usage of `utilities` is misleading. 
<img width="186" alt="Screen Shot 2021-04-04 at 12 05 13 AM" src="https://user-images.githubusercontent.com/2998854/113484160-6ea42f80-94d9-11eb-8177-90074bb74fb8.png">

3. Utilities Class Diagram:  Can consider omit dependency on exception.
<img width="127" alt="Screen Shot 2021-04-04 at 12 10 44 AM" src="https://user-images.githubusercontent.com/2998854/113484309-34875d80-94da-11eb-9a3d-a389314013e2.png"> 

4.  Mixing up roles and labels. Please refer to [this](https://nus-cs2113-ay2021s2.github.io/website/se-book-adapted/chapters/uml.html#roles).

Utilities Class Diagram: 
<img width="585" alt="Screen Shot 2021-04-04 at 12 12 16 AM" src="https://user-images.githubusercontent.com/2998854/113484348-6d273700-94da-11eb-8710-a08e3d44ec77.png">

Command Class Diagram: Seems you intend for these to be labels, but have notated them as roles for `Fridge` and `UI`.  
<img width="220" alt="Screen Shot 2021-04-04 at 12 07 23 AM" src="https://user-images.githubusercontent.com/2998854/113484224-bdea6000-94d9-11eb-8d1f-c6b82622985d.png"> 

5.   Command Class Diagram:  Grammar to be observed in label:
<img width="174" alt="Screen Shot 2021-04-04 at 12 09 45 AM" src="https://user-images.githubusercontent.com/2998854/113484290-11f54480-94da-11eb-819d-6b0fbb9a0866.png">

6. Is food category an enum class? If so, consider separate class to track the quantity.
<img width="156" alt="Screen Shot 2021-04-04 at 12 16 11 AM" src="https://user-images.githubusercontent.com/2998854/113484459-f76f9b00-94da-11eb-9fe6-886070ff5f8a.png">

7. While error handling is important, the exception component section seems too verbose. You could consider summarizing the key points that directly contribute to your product value. 

<img width="672" alt="Screen Shot 2021-04-04 at 12 19 53 AM" src="https://user-images.githubusercontent.com/2998854/113484548-7b298780-94db-11eb-9916-d99960543ca1.png">

8. Object destroyed, lifeline still continues?  
AddCommand seq. diagram: <img width="125" alt="Screen Shot 2021-04-04 at 12 21 12 AM" src="https://user-images.githubusercontent.com/2998854/113484583-aca25300-94db-11eb-847b-e000865d19cb.png">

9.  if condition mentioned in the UML notes - you could use the `opt` instead. 

AddCommand seq. diagram: 
<img width="231" alt="Screen Shot 2021-04-04 at 12 22 26 AM" src="https://user-images.githubusercontent.com/2998854/113484618-d65b7a00-94db-11eb-820b-46a3071e16d6.png">

10. You have three variations of the list command. Keep your diagram simple here by elaborating on one and maybe briefly mention what is different about the other two. 

<img width="377" alt="Screen Shot 2021-04-04 at 12 26 16 AM" src="https://user-images.githubusercontent.com/2998854/113484718-600b4780-94dc-11eb-8b31-a9dbc85206f0.png">

11. Readability is compromised as there is too much detail to describe about the files when this section is for manual testing. You could provide just the two cases of missing or corrupted files and state a simple flow of things for one of the data files. 
<img width="616" alt="Screen Shot 2021-04-04 at 12 33 27 AM" src="https://user-images.githubusercontent.com/2998854/113484896-61893f80-94dd-11eb-9a04-6782a7147207.png">

12. This is better than point 11 as it is clear what to expect from example inputs and test cases. 
<img width="627" alt="Screen Shot 2021-04-04 at 12 32 39 AM" src="https://user-images.githubusercontent.com/2998854/113484881-44547100-94dd-11eb-85e8-fd03fc281368.png">

**Comment by Leeyp** [comment]
Dear @stephlewyh ,

Thank you for your comments!

Regarding point 11, I intentionally made the "Saving data" portion under "Manual testing" verbose, to insure against cheeky testers who attempt to break our code by testing all sorts of invalid corrupted test files, then reporting them as bugs. Since data files have the widest margin for mischief, I believed that having all possibilities spelled out would prevent them from reporting known issues as "bugs". 

Is my assumption wrong? Is there a better way to write the section while keeping in mind adversarial readers/testers?

Thank you very much!

**Comment by kwokyto** [comment]
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
- [ ] 10
- [ ] 11

**Comment by kwokyto** [comment]
- [x] 1 add "homeowner who cooks", change in UG/readme/etc
- [x] 2 add info note below the diagram to clarify that the user interacts with UI in utils
- [x] 3 remove dependency on exception
- [x] 4 fix roles vs labels
- [x] 5 fix grammar
- [x] 6 extract quantity stuff into another class
- [x] 7 shortened part on exceptions
- [x] 8 add note on plantuml
- [x] 9 check if the exception throwing is consistent across all sequence diagrams, add a footnote/info that for simplicity we will express throwing of exceptions in comments of diagrams
- [x] 10 remove 2 and leave 1
- [x] 11 combine all common details
- [x] 12 -

**Comment by Leeyp** [comment]
Same concern for 7), even though the section is lengthy, it is clear and comprehensive, while not compromising on readability as some people who may be more interested in the Exceptions might find it useful (even though most might skim it). Clarity seems to be important here as there might be some weaker/confused readers who might find fault with sections that are not as clear/fleshed out.

Is there any way to improve the section while not compromising on detail/clarity for more nitpicky readers/might raise (invalid) "bugs" over content that is summarized instead of detailed?

**Comment by kwokyto** [comment]
**Steph Comments Summary**

6) extract quantity stuff into another class
7) check if the exception throwing is consistent across all sequence diagrams, add a footnote/info that for simplicity we will express throwing of exceptions in comments of diagrams
11) combine all common details
??) future work —> modify to explain future ideas without mention of food cat
??) hide food category classes in sequence diagram
??) add warning in UG and DG for history data
